---
- include_vars: capture.yml

- name: assemble capture expression
  set_fact:
      expression: "{{ lookup('vars', inventory_hostname, default=dflt) }}"

- name: capture flows
  shell: timeout --signal=SIGTERM {{ stretch }} \
         {{ tcpflow_bin }} \
         -i {{ capture_iface }} \
         -o {{ gather_basin }} \
         -K \
         '{{ expression }}'
  register: outcome
  failed_when:
      - outcome.rc > 0
      - outcome.rc != 124

- name: harvest captures
  import_tasks: _recursive_fetch.yml
