---
# Gathering current kernel TCP flow dynamics preliminary to capture.

- include_vars: sk_stats.yml

- name: gather tcp flow socket stats
  shell: "{{ ss2_cmd }} --tcp --process"
  register: tcp_flows_ctxt

- name: preen tcp flow socket stats
  set_fact:
      tcp_flows_ctxt: "{{ tcp_flows_ctxt.stdout }}"
