---
# tasks file for ansible_distr_pkt_capture

- include_vars: expressions_sample.yml 

- name: gather kernel sk stats 
  import_tasks: flow_sk_ctxt.yml

- name: do capture 
  import_tasks: capture.yml

- name: do flow context association
  import_tasks: associate.yml

- name: do custom pkt processing
  include_tasks: "{{ item }}"
  with_items: "{{ _processing_logic }}"
